DESC GRAUPARENTESCO

INSERT INTO GRAUPAREnTESCO VALUES(1,"Avô");
INSERT INTO GRAUPAREnTESCO VALUES(2,"Avó");
INSERT INTO GRAUPAREnTESCO VALUES(3,"Conjuguê");
INSERT INTO GRAUPAREnTESCO VALUES(4,"Enteado(a)");
INSERT INTO GRAUPAREnTESCO VALUES(5,"Filho(a)");
INSERT INTO GRAUPAREnTESCO VALUES(6,"Mãe");
INSERT INTO GRAUPAREnTESCO VALUES(7,"Neto(a)");
INSERT INTO GRAUPAREnTESCO VALUES(8,"Pai");
INSERT INTO GRAUPAREnTESCO VALUES(9,"Sobrinho(a)");
INSERT INTO GRAUPAREnTESCO VALUES(10,"Tio(a)");

select * from grauparentesco