

insert into corpele values(1,'BRANCA');
insert into corpele values(2,'PRETA');
insert into corpele values(3,'AMARELA');
insert into corpele values(4,'PARDA');
insert into corpele values(5,'INDIGENA')


insert into estadocivil values(1,'SOLTEIRO');
insert into estadocivil values(2,'CASADO');
insert into estadocivil values(3,'SEPARADO');
insert into estadocivil values(4,'DIVORCIADO');
insert into estadocivil values(5,'VIUVO')

DESC LOTACAO

DELETE FROM LOTACAO


INSERT INTO LOTACAO (LOT_cod,lot_desc) values (3,'REITORIA')
INSERT INTO LOTACAO (LOT_cod,lot_desc) values (12,'CAMPUS CURITIBA')
INSERT INTO LOTACAO (LOT_cod,lot_desc) values (8,'REITORIA - PROGEPE')
INSERT INTO LOTACAO (LOT_cod,lot_desc) values (6,'REITORIA - PROPLAN')
INSERT INTO LOTACAO (LOT_cod,lot_desc) values (7,'REITORIA - PRAI')
INSERT INTO LOTACAO (LOT_cod,lot_desc) values (4,'REITORIA - GABINETE')
INSERT INTO LOTACAO (LOT_cod,lot_desc) values (5,'REITORIA - PREPPG')
INSERT INTO LOTACAO (LOT_cod,lot_desc) values (23,'DIR. ADM. E FIN./C. FOZ')
INSERT INTO LOTACAO (LOT_cod,lot_desc) values (36,'CAMPUS UMUARAMA')
INSERT INTO LOTACAO (LOT_cod,lot_desc) values (121,'N.A. ASSIS CHATEAUBRIAND')
INSERT INTO LOTACAO (LOT_cod,lot_desc) values (17,'DIR. GERAL CAMPUS PARANAGUÁ')
INSERT INTO LOTACAO (LOT_cod,lot_desc) values (9,'PRI')
INSERT INTO LOTACAO (LOT_cod,lot_desc) values (16,'CAMPUS PARANAGUÁ')
INSERT INTO LOTACAO (LOT_cod,lot_desc) values (24,'CAMPUS JACAREZINHO')
INSERT INTO LOTACAO (LOT_cod,lot_desc) values (28,'CAMPUS PARANAVAI')
INSERT INTO LOTACAO (LOT_cod,lot_desc) values (117,'CAMPUS LONDRINA')
INSERT INTO LOTACAO (LOT_cod,lot_desc) values (20,'CAMPUS FOZ DO IGUAÇU')
INSERT INTO LOTACAO (LOT_cod,lot_desc) values (112,'CAMPUS PALMAS')
INSERT INTO LOTACAO (LOT_cod,lot_desc) values (18,'DIR. ENC./C. PARANAGUÁ')
INSERT INTO LOTACAO (LOT_cod,lot_desc) values (32,'CAMPUS TELAMACO BORBA')
INSERT INTO LOTACAO (LOT_cod,lot_desc) values (41,'N.A. CAMPO LARGO')
INSERT INTO LOTACAO (LOT_cod,lot_desc) values (21,'DIR. GERAL C. FOZ')
INSERT INTO LOTACAO (LOT_cod,lot_desc) values (116,'N.A. IRATI')

INSERT INTO BANCO values (1,'BANCO DO BRASIL')
INSERT INTO BANCO values (104,'CAIXA ECONOMICA FEDERAL')
INSERT INTO BANCO values (341,'BANCO ITAU')


DELETE FROM GRAUPARENTESCO

INSERT INTO GRAUPARENTESCO values (1,'AVÓS')
INSERT INTO GRAUPARENTESCO values (2,'BISAVÓS')
INSERT INTO GRAUPARENTESCO values (3,'BISNETO(A)')
INSERT INTO GRAUPARENTESCO values (4,'COMPANHEIRO(A)')
INSERT INTO GRAUPARENTESCO values (5,'CONJUGUÊ')
UPDATE grauparentesco SET grau_par_desc = 'CÔNJUGE' WHERE GRAU_PAR_COD = 5
INSERT INTO GRAUPARENTESCO values (6,'ENTEADO(A)')
INSERT INTO GRAUPARENTESCO values (7,'EX-ESPOSA(O)')
INSERT INTO GRAUPARENTESCO values (8,'FILHO(A)')
INSERT INTO GRAUPARENTESCO values (9,'IRMÃO(A)')
INSERT INTO GRAUPARENTESCO values (10,'NETO(A)')
INSERT INTO GRAUPARENTESCO values (11,'PAIS')
INSERT INTO GRAUPARENTESCO values (12,'OUTROS')

SELECT * FROM REGIMETRABALHO
DELETE FROM REGIMETRABALHO

INSERT INTO REGIMETRABALHO values (20,'20 HORAS')
INSERT INTO REGIMETRABALHO values (99,'DEDICAÇÃO EXCLUSIVA')
INSERT INTO REGIMETRABALHO values (24,'24 HORAS')
INSERT INTO REGIMETRABALHO values (30,'30 HORAS')
INSERT INTO REGIMETRABALHO values (40,'40 HORAS')

DESC CARGO

ALTER TABLE CARGO DROP CARG_COD_IDENTIFICADOR

SELECT * FROM CLASSE
DELETE FROM CARGO
INSERT INTO CLASSE VALUES (99,'')


INSERT INTO CARGO VALUES( 1,'ADMINISTRADOR',5);
INSERT INTO CARGO VALUES( 9,'AUDITOR',5);
INSERT INTO CARGO VALUES( 10,'BIBLIOTECARIO',5);
INSERT INTO CARGO VALUES( 15,'CONTADOR',5);
INSERT INTO CARGO VALUES( 29,'ENFERMEIRO',5);
INSERT INTO CARGO VALUES( 31,'ENGENHEIRO',5);
INSERT INTO CARGO VALUES( 32,'ENG. DE SEG. DO TRABALHO',5);
INSERT INTO CARGO VALUES( 45,'JORNALISTA',5);
INSERT INTO CARGO VALUES( 47,'MÉDICO',5);
INSERT INTO CARGO VALUES( 58,'PEDAGOGO',5);
INSERT INTO CARGO VALUES( 62,'ANAL. DE TEC. DA INFORMAÇÃO',5);
INSERT INTO CARGO VALUES( 66,'PROGRAMADOR VISUAL',5);
INSERT INTO CARGO VALUES( 76,'SECRETARIADO EXECUTIVO',5);
INSERT INTO CARGO VALUES( 79,'TEC. EM ASSUN. EDUCACIONAIS',5);
INSERT INTO CARGO VALUES( 200,'ASS. EM ADMINISTRAÇÃO',4);
INSERT INTO CARGO VALUES( 224,'TEC. EM CONTABILIDADE',4);
INSERT INTO CARGO VALUES( 226,'TEC. EM TECNOL. DA INFORMAÇÃO',4);
INSERT INTO CARGO VALUES( 233,'TEC. EM ENFERMAGEM',4);
INSERT INTO CARGO VALUES( 244,'TEC. EM LABORATÓRIO',4);
INSERT INTO CARGO VALUES( 257,'TEC. EM RADIOLOGIA',4);
INSERT INTO CARGO VALUES( 403,'ASS. DE ALUNO',3);
INSERT INTO CARGO VALUES( 409,'AUX. DE BIBLIOTECA',3);
INSERT INTO CARGO VALUES( 421,'CONTINUO',3);
INSERT INTO CARGO VALUES( 422,'CONZINHEIRO',3);
INSERT INTO CARGO VALUES( 436,'IMPRESSOR',3);
INSERT INTO CARGO VALUES( 459,'RECEPCIONISTA',3);
INSERT INTO CARGO VALUES( 464,'TELEFONISTA',3);
INSERT INTO CARGO VALUES( 611,'AUX. DE AGROPECUÁRIA',2);
INSERT INTO CARGO VALUES( 623,'AUX. DE NUTRIÇÃO',2);
INSERT INTO CARGO VALUES( 828,'OPER. DE MAQ. DE LAVANDERIA',1);
INSERT INTO CARGO VALUES( 702001,'PROF. ENS. BAS. TEC. TECNOL.',4);
INSERT INTO CARGO VALUES( 702003,'PROF. ENS. BAS. TEC. TECNOL. - SUB',4);
INSERT INTO CARGO VALUES( 60001,'PROF. DO 3º GRAU',99);
INSERT INTO CARGO VALUES( 60012,'PROF. DO 1º E 2º GRAUS - SUB',99)

DESC DEPENDENTE

DROP TABLE SERVIDORDEPENDENTE

ALTER TABLE DEPENDENTE ADD column serv_cod INTEGER NOT NULL REFERENCES servidor(serv_cod)